In [125]:
import numpy as np 


In [126]:
class Gridworld:

    def __init__(self, shape=(5,5), num_negative_tiles=0, starting_point=(1,1),goal=(3,3)):
        self.size = shape
        self.num_negative_tiles = num_negative_tiles
        self.current_state = starting_point
        self.grid = np.zeros(shape, dtype=np.int64)
        self.stochastic_transistions = np.zeros_like(self.grid,dtype=np.float32)
        self.goal = goal
        self.acc_reward = 0 

        # set values for entries in gridworld (rewards, goal, penalties) non-doable tiles should yield -100
        self.grid[goal[0]][goal[1]] = 100
        # setting borders
        self.grid[0,:] = -100
        self.grid[shape[1]-1,:] = -100
        self.grid[:,0] = -100
        self.grid[:,shape[1]-1] = -100
        # here random negative tiles implementing

        
    # reset the actor to starting state
    def reset(self):
        self.current_state = (1,1)
        self.acc_reward = 0



    def step(self,action):
        '''
        Args:
        action(): 0: right, 1: left, 2, up, 3, down
        throws error if move is invalid due to wall
        '''
        
        # anders ugly mit if elif statements, switch erst ab python 3.10
        # right
        if action == 0:
            # get current state 
            y, x = self.current_state
            # check that current state is accessable
            new_y,new_x = y, x+1
            if self.grid[new_y,new_x] != -100:
                # update current state and collect rewward
                self.current_state = ((new_y, new_x))
                self.acc_reward += self.grid[new_y,new_x]
            else:
                print('Could not move there due to wall.')


        # left step
        elif action == 1:
            # get current state 
            y, x = self.current_state
            # check that current state is accessable
            new_y,new_x = y, x-1
            if self.grid[new_y,new_x] != -100:
                # update current state and collect rewward
                self.current_state = ((new_y, new_x))
                self.acc_reward += self.grid[new_y,new_x]
            else:
                print('Could not move there due to wall.')

        # upwards step
        elif action == 2:
            # get current state 
            y, x = self.current_state
            # check that current state is accessable
            new_y,new_x = y-1, x
            if self.grid[new_y,new_x] != -100:
                # update current state and collect rewward
                self.current_state = ((new_y, new_x))
                self.acc_reward += self.grid[new_y,new_x]
            else:
                print('Could not move there due to wall.')
        
        # downwards step
        elif action == 3:
            # get current state 
            y, x = self.current_state
            # check that current state is accessable
            new_y,new_x = y+1, x
            if self.grid[new_y,new_x] != -100:
                # update current state and collect rewward
                self.current_state = ((new_y, new_x))
                self.acc_reward += self.grid[new_y,new_x]
            else:
                print('Could not move there due to wall.')

        

    def visualize(self):
        print(self.grid)






In [127]:
grid = Gridworld(shape=(10,10), goal=(8,8))
grid.step(2)
grid.visualize()

Could not move there due to wall.
[[-100 -100 -100 -100 -100 -100 -100 -100 -100 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0    0 -100]
 [-100    0    0    0    0    0    0    0  100 -100]
 [-100 -100 -100 -100 -100 -100 -100 -100 -100 -100]]
